FROM stilliard/pure-ftpd


RUN echo -e 'marc:$6$qb43s/.rtDb9WTU0$ZpgMF2egW1EbHjpZlS4sU5nREbXGcGGtrOpQlfi.Khg1gR05DIVcw5Id5iEfPUFHHgIzltX2BfthMNinbsMAP0:1000:1000::/data/./::::::::::::' >> /etc/pure-ftpd/passwd/pureftpd.passwd 
echo -e "PUTA GORDA MARC"
